### ISSUE TITLE
Необработанное исключение Android

### ISSUE THREAD

**Issue by SatoruReed** [NightStrang6r/FunPayServer#15]
Ошибка: необработанное исключение. Сообщите об этом разработчику.
> [14.03.2023] [20:19:29]: Error: 409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at Telegram.callApi (/data/data/com.termux/files/home/FunPayServer-main/node_modules/telegraf/lib/core/network/client.js:293:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async [Symbol.asyncIterator] (/data/data/com.termux/files/home/FunPayServer-main/node_modules/telegraf/lib/core/network/polling.js:30:33)
    at async Polling.loop (/data/data/com.termux/files/home/FunPayServer-main/node_modules/telegraf/lib/core/network/polling.js:73:30)
    at async Telegraf.launch (/data/data/com.termux/files/home/FunPayServer-main/node_modules/telegraf/lib/telegraf.js:189:13)

**Comment by NightStrang6r** [comment]
В одно время может быть запущен только 1 экземпляр телеграм бота. При запуске нового, предыдущий закроется с такой ошибкой.
